### ISSUE TITLE
Cannot Post a Post

### ISSUE THREAD

**Issue by schaefa** [auniverseaway/slick-2#2]
After installing Slick 2 using a clone of this GIT repo and Sling 8 I failed to post a Post and a new and empty installation. I tried with Safari and Chrome and both show the same issue. 

java.lang.NullPointerException: name
    at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.create(ResourceResolverImpl.java:1116)
    at org.millr.slick.servlets.item.EditItemServlet.doPost(EditItemServlet.java:156)
    at org.apache.sling.api.servlets.SlingAllMethodsServlet.mayService(SlingAllMethodsServlet.java:149)
    at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:345)
    at org.apache.sling.api.servlets.SlingSafeMethodsServlet.service(SlingSafeMethodsServlet.java:376)
    at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:546)
    at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:44)
    at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
    at org.apache.sling.engine.impl.SlingRequestProcessorImpl.processComponent(SlingRequestProcessorImpl.java:282)
    at org.apache.sling.engine.impl.filter.RequestSlingFilterChain.render(RequestSlingFilterChain.java:49)
    at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
    at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:129)

**Comment by auniverseaway** [comment]
Pull latest. This should be fixed.

What it was: The node name input field was disabled, and thus, was not picked up by the servlet.
